### PR TITLE
Replace Travis badge

### PR DESCRIPTION
**Pull request by tetienne**
The build is not anymore on Travis but on Github Action.

### CODE REVIEW

**Comment by tetienne** [comment]
@Quentame are you the one that own this repo?

**Review by Quentame — APPROVED** [review]

**Comment by Quentame** [comment]
Yep

**Comment by tetienne** [comment]
@Quentame Thx. Perhaps can we add a [code owner file](https://docs.github.com/en/github-ae@latest/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax) to automatically add you as reviewer?

**Comment by Quentame** [comment]
Yep indeed.
Will look at other PRs too.

**Pull request merged**
